FROM meltwater/secretary:0.8.0

ADD config-private-key.pem   /keys/config-private-key.pem
ADD config-public-key.pem  /keys/config-public-key.pem
ADD master-private-key.pem  /keys/master-private-key.pem
ADD master-public-key.pem /keys/master-public-key.pem
