zookeeper:
  image: mesoscloud/zookeeper:3.4.6-centos-7
  ports:
    - "2181:2181"
    - "2888:2888"
    - "3888:3888"
  environment:
    SERVERS: 'server.1=127.0.0.1'
    MYID: '1'

mesosmaster:
  image: mesosphere/mesos-master:0.27.0-0.2.190.ubuntu1404
  net: host
  volumes:
    - /var/log/mesos/master
  environment:
    MESOS_ZK: 'zk://localhost:2181/mesos'
    MESOS_QUORUM: '1'
    MESOS_CLUSTER: 'local'
    MESOS_HOSTNAME: '192.168.99.100'
    MESOS_LOG_DIR: '/var/log/mesos/master'

mesosslave:
  build: mesos-slave
  net: host
  privileged: true
  volumes:
    - /var/log/mesos/slave
    - /sys:/sys
# /cgroup is needed on some older Linux versions
#    - /cgroup:/cgroup
# /usr/bin/docker is needed if you're running an older docker version
    - /usr/local/bin/docker:/usr/bin/docker:ro
    - /var/run/docker.sock:/var/run/docker.sock:rw
  environment:
    MESOS_MASTER: 'zk://localhost:2181/mesos'
    MESOS_PORT: '5051'
    MESOS_LOG_DIR: '/var/log/mesos/slave'
    MESOS_CONTAINERIZERS: 'docker,mesos'
    MESOS_EXECUTOR_REGISTRATION_TIMEOUT: '5mins'
    MESOS_EXECUTOR_SHUTDOWN_GRACE_PERIOD: '90secs'
    MESOS_DOCKER_STOP_TIMEOUT: '60secs'
# If your workstation doesn't have a resolvable hostname/FQDN then $MESOS_HOSTNAME needs to be set to its IP-address
    MESOS_HOSTNAME: 192.168.99.100

marathon:
  image: mesosphere/marathon:v0.15.1
  net: host
  environment:
    MARATHON_ZK: 'zk://localhost:2181/marathon'
    MARATHON_MASTER: 'zk://localhost:2181/mesos'
    MARATHON_EVENT_SUBSCRIBER: 'http_callback'
    MARATHON_TASK_LAUNCH_TIMEOUT: '300000'

marathonsubmit:
  build: marathon-submit
  net: host
  environment:
    MARATHON_URL: http://localhost:8080
  volumes:
    - './marathon-submit:/submit'
## Enables using local development repo of lighter
##    - '../lighter:/lighter'


gateway:
  image: meltwater/proxymatic:1.7.5
#  build: ../proxymatic
  net: host
  environment:
    MARATHON_URL: 'http://localhost:8080'
    MARATHON_CALLBACK_URL: 'http://localhost:5090'
    EXPOSE_HOST: 'true'
    VHOST_DOMAIN: 'localdomain'
#    HAPROXY: 'true'
    VERBOSE: 'true'

secretary:
  build: ./secretary
#  image: meltwater/secretary-fixed:latest
  net: host
#  volumes:
#    - './marathon-submit/site/keys:/keys'
